name: m169-abschlussprojekt

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: m169-portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "${PORTAINER_HTTPS_PORT:-9443}:9443"
      - "${PORTAINER_HTTP_PORT:-9000}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - frontend

networks:
  frontend:
    name: m169_frontend
  backend:
    name: m169_backend
    internal: true

volumes:
  # Portainer
  portainer_data:

  # Gitea ("Gitty")
  gitea_data:
  gitea_db:

  # Nextcloud
  nextcloud_data:
  nextcloud_db:
  nextcloud_redis:

  # MediaWiki
  mediawiki_data:
  mediawiki_db:
